### Register

POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "user5",
    "password": "pass5"
}

### Login

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "user5",
    "password": "pass5"
}

### Generate access token

POST http://localhost:8080/api/auth/token HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI1IiwiaWF0IjoxNjE2Njg4ODg1fQ._3Ml5Fb2njq7sHGkXPa6tE65Wu1YAlbQxTcByuFrDv8"
}

###

DELETE http://localhost:8080/api/auth/logout HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWF0IjoxNjEwNjI1MTg0fQ.YscWEL4uhpzsR3Sn37K9tRwKWYk5SkJsBI2uG2eEKpQ"
}
