### Register

POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "user5",
    "password": "pass5"
}

### Login

POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "user5",
    "password": "pass5"
}

### Generate access token

POST http://localhost:8080/api/auth/token HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI1IiwiaWF0IjoxNjIzODM3Nzg2fQ.ENQE3i6GtLbwbBfFuz3thj581fXNIa0PbuwhnMVR-Tk"
}

###

DELETE http://localhost:8080/api/auth/logout HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI1IiwiaWF0IjoxNjIzODM3Nzg2LCJleHAiOjE2MjM4NDEzODZ9.y-BtmeV3ishY7qhEC6vw2oYnoVFge9AXj9u4rrsCXC0"
}
