### Create new route
POST http://localhost:8080/api/dynamicRoutes HTTP/1.1
Content-Type: application/json

{
    "method": "get",
    "path": "/test",
    "response": {
        "body": {
            "key": "value"
        },
        "status": 200
    }
}

### Get information about specific routes
GET http://localhost:8080/api/dynamicRoutes?method=get&path=/test HTTP/1.1

### Get information about all routes
GET http://localhost:8080/api/dynamicRoutes HTTP/1.1

### Go to the created route
GET http://localhost:8080/api/dynamicRoutes/test HTTP/1.1

###Delete a route
DELETE http://localhost:8080/api/dynamicRoutes HTTP/1.1
Content-Type: application/json

{
    "method": "get",
    "path": "/test"
}
